### ISSUE TITLE
Did not autorun on reboot/startup on Raspbian

### ISSUE THREAD

**Issue by andrewdhastings** [balena-os/wifi-connect#231]
Not sure if this is a bug, or lack of understanding on configuration. However, after installing Wifi Connect on a Pi 3 and rebooting, nothing happened. I was expecting it to automatically launch and create the network. 

However, I had to SSH back in and run 'sudo wifi-connect' to get the program to run, at that point everything seamed to work correctly. Is this a bug, or a configuration issue?

**Comment by majorz** [comment]
@andrewdhastings This should be a configuration issue. Can you please paste if possible your start script and Dockerfile so that I can take a look at those.

**Comment by andrewdhastings** [comment]
I used the Bash/curl link to install on a fresh raspbian stretch lite image. Never adjusted the config. 

⁣Sent from BlueMail ​

**Comment by majorz** [comment]
I see, you used Raspbian, not Resin OS. There is not autorun for Raspbian yet included. I think I can add it since it will not be complicated.

**Comment by majorz** [comment]
Autorun can be enabled by creating a systemd unit file that executes a shell script that starts WiFi Connect. The systemd unit should be a one-shot service that starts after NetworkManager. That will be relatively easy to add.

The shell script will be very similar to our example resin OS start script: https://github.com/resin-io/resin-wifi-connect/blob/master/scripts/start.sh

I am going include autorun functionality for Raspbian in the install script after implementing #234.

**Comment by libbymiller** [comment]
(belatedly) - I got it working nicely on a Pi. Thank you for doing it! https://planb.nicecupoftea.org/2019/01/11/balneas-wifi-connect-easy-wifi-for-raspberry-pis/

**Comment by arsoba** [comment]
There is could be a problem with systemd service. If start.sh runs after NetworkManager there is could be following problem NetworkManager is running but not connecting to WiFi. Start.sh checks WIFi connection and doesn’t find one and start wifi-connect.

**Comment by majorz** [comment]
@arsoba please take a look at the `nm-online` utility that NetworkManager provides, as I think it may be a very good substitute for `iwgetid` for running wifi-connect on Raspbian: https://developer.gnome.org/NetworkManager/stable/nm-online.html

This should indicate much more precisely whether wifi-connect should be started or not.
