### ISSUE TITLE
Error when building wifi-connect with balena cli for raspberry pi zero w

### ISSUE THREAD

**Issue by PastaGringo** [balena-os/wifi-connect#351]
Hi,

I'm using a raspberry pi zero w and I want to test to deploy Wifi-Connect but I have an issue during the build.

Here is my docker-compose file:

```
version: "2.1"
services:
  wifi-connect:
     build: wifi-connect
     network_mode: "host"
     labels:
       io.balena.features.dbus: '1'
     cap_add:
       - NET_ADMIN
     environment:
       DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
```

When I try to build the application with balena cli with the command `balena deploy NameOfMyApp --logs --source .` 
I have the error above:

```
(node:10018) ExperimentalWarning: The fs.promises API is experimental
[Info]    Building for rpi/raspberry-pi
[Build]   Building services...
[Build]   wifi-connect Preparing...
[Info]    Docker Desktop detected (daemon architecture: "x86_64")
[Info]      Docker itself will determine and enable architecture emulation if required,
[Info]      without balena-cli intervention and regardless of the --emulated option.
[Build]   wifi-connect Step 1/6 : FROM balenalib/raspberry-pi-debian
[Build]   wifi-connect  ---> f1fd84b0cf9d
[Build]   wifi-connect Step 2/6 : RUN install_packages dnsmasq wireless-tools
[Build]   wifi-connect  ---> Running in b6194655ce2a
[Build]   wifi-connect /lib/ld-linux-armhf.so.3: No such file or directory
[Build]   Built 1 service in 0:01
[Error]   Deploy failed
The command '/bin/sh -c install_packages dnsmasq wireless-tools' returned a non-zero code: 255

Additional information may be available with the `--debug` flag.
For help, visit our support forums: https://forums.balena.io
For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/
```

Error seems to be `The command '/bin/sh -c install_packages dnsmasq wireless-tools' returned a non-zero code: 255`
Does the image raspberry-pi-debian is not the right one ?

Because when I check here : https://www.balena.io/docs/reference/base-images/base-images/
I can read:
`Devices with a device type of raspberry-pi (Raspberry Pi1 and Zero) will be built from balenalib/rpi-raspbian and will be Raspbian base images. The raspberry-pi2 and raspberrypi3 device types Debian base images have the Raspbian package source added, and Raspbian userland pre-installed.`

Thanks for your help!

**Comment by fencer** [comment]
did you ever get this solved?

**Comment by alexszilagyi** [comment]
@PastaGringo , @fencer : any updates regarding to this issue?

**Comment by alexszilagyi** [comment]
UPDATE: 

The following commands seemed to work for me:
```
balena build --deviceType raspberry-pi --arch rpi --emulated
balena deploy <app-name> --source <path-to-multi-container>
```
