### ISSUE TITLE
Access point is not working

### ISSUE THREAD

**Issue by subhadeep-123** [balena-os/wifi-connect#385]
![image](https://user-images.githubusercontent.com/42332939/112674718-463e8480-8e8c-11eb-9b54-8428942e7cf2.png)

It is showing an access point created in Balena Dashboard but no access point named wifi-connect is being created, tried rebooting, restarting, and some other ways but nothing seems to be working.

**Comment by airdrummingfool** [comment]
Is it possible that the container actually already has internet access (e.g. is the Pi plugged into a LAN)? wifi-connect runs its own access check (even if you manually launch it), and if it detects an internet connection it will print output indicating it is starting an AP, but it won't actually start one. See my issue #378 for more info and my feature request to fix this.
