### ISSUE TITLE
Raspbian install broken because of repo move to `balena-os` organization

### ISSUE THREAD

**Issue by Ereski** [balena-os/wifi-connect#389]
The raspbian install script does not work anymore: https://github.com/balena-os/wifi-connect/blob/master/scripts/raspbian-install.sh#L175

**Comment by Ereski** [comment]
I'm not sure if this is actually an intentional change or not, since I can't find any mention of this

**Comment by majorz** [comment]
I changed the title as the API correctly returns a JSON from that link. The reason for the breakage is that the repo was moved to `balena-os` organization and an internal regex in the installer broke matching towards that JSON. The regex is used to extract the real binary download link. (not the most elegant way of parsing JSON, but shell script with default tools installed :/)
