### ISSUE TITLE
Raspberri 4 problem

### ISSUE THREAD

**Issue by Catta1997** [balena-os/wifi-connect#550]
Hi, i have a problem in Raspberry 4, I already changed the line in install.sh but I'm installing the v 4.4.6 , I dot know if it is fixed in newer version but my raspberry when I input a new wifi in portal and press "connect" not connect to the wifi. I tried with multiple AP also sometimes (9/10 times) not automatically start

**Comment by Zandor300** [comment]
Using v4.11.1 should work. Could you try that?

**Comment by nogoonoo** [comment]
@Zandor300  - I'm encountering the same issue as @Catta1997 .  Are there instructions anywhere on how to download previous versions?  Thanks!

**Comment by nogoonoo** [comment]
Thanks @Zandor300 ! I'll give it a go

**Comment by nogoonoo** [comment]
It is installed, but I don’t see the AP on my RP4. Is there a command I need to run?On Apr 12, 2024, at 1:23 AM, Sinon ***@***.***> wrote:﻿

Thanks @Zandor300 ! I'll give it a go

let me know if worked
