### ISSUE TITLE
cannot connect to AP on rpi4

### ISSUE THREAD

**Issue by bagges** [balena-os/wifi-connect#564]
I am running wifi-connect inside a container on a raspberry pi 4, but I am not able to connect to the access point. On the very first time I was able to connect, but after that I end up with the following errors. Even deleting the container or rebooting the system does not help. Any idea? Thanks.

### container log
```
Attaching to tmp_wifi-connect_1
wifi-connect_1  | Starting WiFi Connect
wifi-connect_1  | Deleting already created by WiFi Connect access point connection profile: "WiFi Connect"
wifi-connect_1  | [<unknown>:WARN] Undefined device type: 32
wifi-connect_1  | WiFi device: wlan0
wifi-connect_1  | Access points: ["WiFi Connect"]
wifi-connect_1  | Starting access point...
wifi-connect_1  | Access point 'WiFi Connect' created
wifi-connect_1  | Starting HTTP server on 192.168.42.1:8081
```

### dmesg output
```
[  464.507891] warning: `iwgetid' uses wireless extensions which will stop working for Wi-Fi 7 hardware; use nl80211
[  465.007742] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
[  465.008115] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
[  468.932915] brcmfmac: brcmf_set_channel: set chanspec 0x100c fail, reason -52
[  468.933319] brcmfmac: brcmf_set_channel: set chanspec 0x100d fail, reason -52
[  468.933696] brcmfmac: brcmf_set_channel: set chanspec 0x100e fail, reason -52
[  468.934073] brcmfmac: brcmf_set_channel: set chanspec 0xd022 fail, reason -52
[  469.044883] brcmfmac: brcmf_set_channel: set chanspec 0xd026 fail, reason -52
[  469.152384] brcmfmac: brcmf_set_channel: set chanspec 0xd02a fail, reason -52
[  469.260967] brcmfmac: brcmf_set_channel: set chanspec 0xd02e fail, reason -52
```

### wpa_supplicant log
```
May 13 22:44:37 myhost wpa_supplicant[662]: Note: nl80211 driver interface is not designed to be used with ap_scan=2; this can result in connection failures
```

**Comment by bagges** [comment]
Okay, as stated in the readme the onboard chip seems not to be supported...

**Comment by tm-sanjay** [comment]
@bagges how did you solve this, I'm also getting ** [<unknown>:WARN] Undefined device type: 32**. Everything was working for the first after apt upgrade, it's not connecting to AP no other errors

**Comment by bagges** [comment]
> how to solve this, I'm also getting ** [:WARN] Undefined device type: 32**. Everything was working for the first after apt upgrade, it's not connecting to AP no other errors

Are you using a PI4? The chipset is not supported, I did not get it running reliable...

**Comment by tm-sanjay** [comment]
No, actually I'm using Rock pi E, the chip is supported. I have used it for over a year with Armbian 22.1, and it worked fine.  Now I switch to Armbian 24.8.3 Bookworm, it gives me this warning. and now able to connect to the wifi AP, but it is showing up in the Wi-Fi scan
